#ifndef __BACNET_HONEYWELL_H_INCLUDED

#define BACNET_HONEYWELL_DEV_VENDOR_NAME "Honeywell"
#define BACNET_HONEYWELL_DEV_VENDOR_ID 17


////////////////////////////////////////////////////////////
// private transfer Message definition
// THESE ID'S MUST BE UNIQUE FOR ALL HONEYWELL DEVICES!!!!!
typedef enum E_BACNET_HONEYWELL_PRIVATE_TRANSFER_MSG_IDS {
  BACNET_HONEYWELL_PRIV_SERV_NULL                          = 0
#ifdef XLWEB_VERSION_1_XX
   ,BACNET_HONEYWELL_PRIV_SERV_SESSION_SYNC_WITHIN_PROJECT   = 70 // [GBA] 15. Oct 2014, deprecated for security reasons
//   ,BACNET_HONEYWELL_PRIV_SERV_SESSION_SYNC                = 77 // deprecated!
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC                   = 80
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC_CYCLIC            = 81
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC_REQ_MIS_IDENT_OBJ = 82
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC_REQ_MOD_IDENT_OBJ = 83
   ,BACNET_HONEYWELL_PRIV_SERV_WHO_HAS_OBJ_ID_WITHIN_PROJECT = 90
   ,BACNET_HONEYWELL_PRIV_SERV_I_HAVE_OBJ_ID_WITHIN_PROJECT  = 91
   ,BACNET_HONEYWELL_PRIV_SERV_MULTIBLOCK                    = 100
   ,BACNET_HONEYWELL_PRIV_SERV_UNCONF_COV_NOTIFICATION       = 101
#else
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC                   = 103
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC_CYCLIC            = 104
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC_REQ_MIS_IDENT_OBJ = 105
   ,BACNET_HONEYWELL_PRIV_SERV_OBJECT_SYNC_REQ_MOD_IDENT_OBJ = 106
   ,BACNET_HONEYWELL_PRIV_SERV_SESSION_SYNC_WITHIN_PROJECT   = 110 // [GBA] 15. Oct 2014, deprecated for security reasons
   ,BACNET_HONEYWELL_PRIV_SERV_WHO_HAS_OBJ_ID_WITHIN_PROJECT = 111 // [GBA] 7. Mar. 2013 changed the service ID!
   ,BACNET_HONEYWELL_PRIV_SERV_I_HAVE_OBJ_ID_WITHIN_PROJECT  = 112 // [GBA] 7. Mar. 2013 changed the service ID!
   ,BACNET_HONEYWELL_PRIV_SERV_MULTIBLOCK                    = 120 // [GBA] 7. Mar. 2013 changed the service ID!
   ,BACNET_HONEYWELL_PRIV_SERV_UNCONF_COV_NOTIFICATION       = 121 // [GBA] 7. Mar. 2013 changed the service ID!
#endif
   ,BACNET_HONEYWELL_PRIV_SERV_YOU_ARE                       = 124 // [GBA] 27. Aug. 2015 intermediate solution until proposal STK-034 is accepted by the SSPC
                                                  // see PT_SERVICE_YOU_ARE in FreeRange BACnet stack!!!
   ,BACNET_HONEYWELL_PT_SERVICE_SET_PASSWORD                 = 125 // [GBA] 5. Oct. 2015

   ,BACNET_HONEYWELL_PRIV_SERV_WHO_AM_I                      = 130 // [WSC] 01. Dec. 2017
   ,BACNET_HONEYWELL_PRIV_SERV_TAGGED_VALUE                  = 131 // [SRCW] 17 Sep. 2018
   ,BACNET_HONEYWELL_PRIV_SERV_WIFI_REJOIN                   = 160 // [LJX] 17 Mar. 2020
} BACNET_HONEYWELL_PRIVATE_TRANSFER_MSG_IDS_t;

#endif /* #ifndef __BACNET_HONEYWELL_H_INCLUDED */
